/*
 * Copyright(c) 1997-2001 id Software, Inc.
 * Copyright(c) 2002 The Quakeforge Project.
 * Copyright(c) 2006 Quetoo.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#pragma once

#include <stddef.h>

#include <Objectively/Vector.h>

#include "shared/shared.h"
#include "collision/cm_types.h"
#include "game/common/bg_hook.h"
#include "bg_item.h"
#include "bg_pmove.h"
#include "game/game.h"
#include "race_admin_types.h"
#include "race_physics.h"
#include "race_training.h"
#include "race_types.h"

/**
 * @brief The name this module answers to: its directory under lib/quetoo, and
 * the game_name it advertises.
 */
#define GAME_NAME "race"

/**
 * @brief Game protocol version (protocol minor version). To be incremented
 * whenever the game protocol changes.
 */
#define PROTOCOL_MINOR 1066

/**
 * @brief Game-specific server protocol commands. These are parsed directly by
 * the client game module.
 */
typedef enum {
  SV_CMD_SOUND = SV_CMD_CGAME,
  SV_CMD_MUZZLE_FLASH,
  SV_CMD_TEMP_ENTITY,
  SV_CMD_VIEW_KICK,
  SV_CMD_CENTER_PRINT,
  SV_CMD_SCORES,
  SV_CMD_SNAP_ANGLES,
  SV_CMD_RACE_REPLAY_STATE,
  SV_CMD_RACE_REPLAY_TELEMETRY,
  SV_CMD_RACE_REPLAY_PROJECTILES,
  SV_CMD_RACE_RACELINE,
  SV_CMD_RACE_MAP_BROWSER,
  SV_CMD_RACE_MAP_BROWSER_DETAIL,
  SV_CMD_RACE_FINISH_REPORT,
  SV_CMD_RACE_SPLIT,
  SV_CMD_RACE_WEAPON_TUNING,
  SV_CMD_RACE_ADMIN_CHALLENGE,
  SV_CMD_RACE_PROFILE_REQUEST,
  SV_CMD_RACE_PROFILE_CHALLENGE,
  SV_CMD_RACE_PROFILE_ENROLLMENT,
} g_sv_packet_cmd_t;

/**
 * @brief Game-specific client protocol commands. These are parsed directly by
 * the game module.
 */
typedef enum {
  CL_CMD_EXAMPLE = CL_CMD_CGAME,
} g_cl_packet_cmd_t;

/**
 * @brief The name of the map list generated by the user interface.
 */
#define MAP_LIST_UI "maps.ui.lst"

/**
 * @brief ConfigStrings that are local to the game module.
 */
#define CS_GAMEPLAY        (CS_GAME + 0)  // gameplay string
#define CS_TEAM_INFO       (CS_GAME + 1)  // team info, separated by \ (name\color\name\color, etc)
#define CS_TIME            (CS_GAME + 2)  // map time
#define CS_MAX_CLIENTS     (CS_GAME + 3)  // max clients of server
#define CS_NUM_CLIENTS     (CS_GAME + 4)  // number of players in server
#define CS_NUM_TEAMS       (CS_GAME + 5)  // number of teams (0 - MAX_TEAMS)
#define CS_NAV_EDIT        (CS_GAME + 6)  // nav edit mode
#define CS_ITEM_SET        (CS_GAME + 7)  // active item set (g_items_t)
#define CS_RACE_CHECKPOINT_TOTAL (CS_GAME + 8) // validated Race checkpoint total
#define CS_RACE_PHYSICS_CONFIG (CS_GAME + 9) // versioned map-fixed physics identity
#define CS_HOOK_PULL_SPEED (CS_GAME + 10) // hook speed used by prediction
#define CS_RACE_LEADERBOARD (CS_GAME + 11) // v1\count\name\time_ms\date_unix_s...
#define CS_RACE_VOTE_INFO (CS_GAME + 12) // active yes/no vote status
#define CS_RACE_VOTE_MENU (CS_GAME + 13) // end-of-map map-choice vote
#define CS_RACE_WEAPON_TUNING_STATUS (CS_GAME + 14) // compact authoritative tuning state
#define CS_RACE_SETTINGS_STATUS (CS_GAME + 15) // GSET/MSET registry state mirror

/**
 * @brief Player state statistics (inventory, score, etc).
 */
typedef enum {
  STAT_ARMOR,
  STAT_CHASE,
  STAT_DAMAGE_ARMOR,
  STAT_DAMAGE_HEALTH,
  STAT_DAMAGE_INFLICT,
  STAT_DEATHS,
  STAT_FRAGS,
  STAT_HEALTH,
  STAT_INVISIBILITY_TIME,
  STAT_INVULNERABILITY_TIME,
  STAT_PICKUP,
  STAT_QUAD_TIME,
  STAT_SCORES,
  STAT_SPECTATOR,
  STAT_TEAM,
  STAT_TIME,
  STAT_WEAPON,
  STAT_RACE_MODE,
  STAT_RACE_RUN_STATE,
  STAT_RACE_ELAPSED_LOW,
  STAT_RACE_ELAPSED_HIGH,
  STAT_RACE_CHECKPOINT_COUNT,
  STAT_RACE_INVALID_FLAGS,
  STAT_RACE_INPUT,
  STAT_RACE_PB_LOW,
  STAT_RACE_PB_HIGH,
  STAT_RACE_WR_LOW,
  STAT_RACE_WR_HIGH,
  STAT_RACE_ADMIN_CAPABILITIES,
  STAT_RACE_VOTE_FLAGS
} g_stat_t;

_Static_assert(STAT_RACE_VOTE_FLAGS < MAX_STATS,
               "Race player statistics exceed MAX_STATS");

/**
 * @brief Per-client voting capabilities carried in STAT_RACE_VOTE_FLAGS.
 *
 * The valid bit makes this additive wire extension compatible with older Race
 * game modules: newer cgame modules can retain their legacy gating when it is
 * absent instead of treating a zero-filled, unknown statistic as authoritative.
 */
typedef enum {
  RACE_VOTE_CLIENT_STATE_VALID = 1u << 0u,
  RACE_VOTE_CLIENT_CAN_CAST = 1u << 1u,
  RACE_VOTE_MENU_CLIENT_CAN_CAST = 1u << 2u,
  RACE_VOTE_MENU_CLIENT_CAN_NOMINATE = 1u << 3u
} race_vote_client_flag_t;

/**
 * @brief Forces a statistic field to be re-sent, even if the value has not changed.
 */
#define STAT_TOGGLE_BIT 0x4000

/**
 * @brief Sentinel for muzzle flashes emitted by non-transmitted entities.
 */
#define MUZZLE_FLASH_WORLD -1

/**
 * @brief The muzzle flash effects the client game can render.
 */
typedef enum {
  MZ_BLASTER,
  MZ_SHOTGUN,
  MZ_SUPER_SHOTGUN,
  MZ_MACHINEGUN,
  MZ_GRENADE_LAUNCHER,
  MZ_ROCKET_LAUNCHER,
  MZ_HYPERBLASTER,
  MZ_LIGHTNING,
  MZ_RAILGUN,
  MZ_BFG10K,
  MZ_LOGOUT,

  MZ_QUAKE_SHOTGUN,
  MZ_QUAKE_SUPER_SHOTGUN,
  MZ_QUAKE_NAILGUN,
  MZ_QUAKE_SUPER_NAILGUN,
  MZ_QUAKE_GRENADE_LAUNCHER,
  MZ_QUAKE_ROCKET_LAUNCHER,

  MZ_LASER,
} g_muzzle_flash_t;

/**
 * @brief Temporary entities are positional events that are not explicitly
 * bound to a game entity (`g_entity_t`). Examples are explosions, certain weapon
 * trails and other short-lived effects.
 */
typedef enum {
  TE_TELEPORT,
  TE_BLASTER,
  TE_TRACER,
  TE_BULLET,
  TE_BLOOD,
  TE_SPARKS,
  TE_HYPERBLASTER,
  TE_LIGHTNING_DISCHARGE,
  TE_RAIL,
  TE_EXPLOSION,
  TE_BUBBLES,
  TE_BFG_LASER,
  TE_BFG_LASER_DEAD,
  TE_BFG,
  TE_GIB,
  TE_RIPPLE,
  TE_HOOK_IMPACT,
  TE_NAIL,
  TE_AI_NODE,
  TE_AI_NODE_LINK
} g_temp_entity_t;

/**
 * @brief Sound playback flags.
 */
#define SOUND_ENTITY    (1 << 0)
#define SOUND_ORIGIN    (1 << 1)
#define SOUND_PITCH     (1 << 2)
#define SOUND_GAIN      (1 << 3)
#define SOUND_RELATIVE  (1 << 4)

/**
 * @brief Sound playback dispatch. Sounds may be associated with an entity, or simply positioned.
 */
typedef struct {

  /**
   * @brief ConfigString index of the sample to play.
   */
  int32_t index;

  /**
   * @brief Sound flags; see SOUND_*.
   */
  int32_t flags;

  /**
   * @brief Entity to bind the sound to for positioning.
   */
  const struct g_entity_s *entity;

  /**
   * @brief Sound origin, takes precedence over the entity origin.
   */
  const vec3_t *origin;

  /**
   * @brief Pitch shift in tones; 8 tones per octave.
   */
  int8_t pitch;

  /**
   * @brief Gain scalar in [0, 1]; 0 means use the default (1.0).
   */
  float gain;
} g_play_sound_t;

/**
 * @brief Player scores are transmitted as binary to the client game module.
 */
typedef struct {

  /**
   * @brief Client number.
   */
  uint16_t client;

  /**
   * @brief Round-trip latency in milliseconds.
   */
  int16_t ping;

  /**
   * @brief Team or player color hue.
   */
  int16_t color;

  /**
   * @brief Frag or point score.
   */
  int16_t score;

    /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief Score flags.
   */
  uint8_t flags;

  /**
   * @brief Team index.
   */
  uint8_t team;

  /**
   * @brief Current or final Race elapsed time in milliseconds.
   */
  uint32_t race_elapsed_time;

  /**
   * @brief Number of logical Race checkpoints completed.
   */
  uint16_t race_checkpoint_count;

  /**
   * @brief Authoritative Race participation mode.
   */
  uint8_t race_mode;

  /**
   * @brief Authoritative Race run state.
   */
  uint8_t race_run_state;

  /**
   * @brief Legacy-compatible reasons the current Race run is unrankable.
   */
  uint8_t race_invalid_flags;
} g_score_t;

/**
 * @brief Player scores flags.
 */
#define SCORE_SPECTATOR (1 << 2)
#define SCORE_AGGREGATE (1 << 3)

/**
 * @brief Game-specific entity events.
 */
typedef enum {
  EV_CLIENT_TELEPORT = EV_GAME,
  EV_CLIENT_DROWN,
  EV_CLIENT_FALL,
  EV_CLIENT_FALL_FAR,
  EV_CLIENT_FOOTSTEP,
  EV_CLIENT_GURP,
  EV_CLIENT_JUMP,
  EV_CLIENT_LAND,
  EV_CLIENT_SIZZLE,
  EV_ITEM_RESPAWN,
  EV_ITEM_PICKUP,
  EV_CLIENT_RAGDOLL,
} g_entity_event_t;

/**
 * @brief Game-specific entity state effects.
 */
#define EF_ROTATE          (EF_GAME << 0) // rotate on z
#define EF_BOB             (EF_GAME << 1) // bob on z
#define EF_INACTIVE        (EF_GAME << 2) // inactive icon for when input is not going to game
#define EF_BEAM            (EF_GAME << 3) // overloads old_origin for endpoint
#define EF_CORPSE          (EF_GAME << 4) // to differentiate own corpse from self
#define EF_RESPAWN         (EF_GAME << 5) // yellow shell
#define EF_QUAD            (EF_GAME << 6) // blue-green shell
#define EF_RACE_GATE       (EF_GAME << 7) // prediction-filtered Race barrier
#define EF_DESPAWN         (EF_GAME << 11) // translucent
#define EF_LIGHT           (EF_GAME << 12) // colored light
#define EF_LIGHT_PULSE     (EF_GAME << 13) // pulse EF_LIGHT radius
#define EF_TEAM_TINT       (EF_GAME << 14) // tint by the team color provided
#define EF_INVISIBILITY    (EF_GAME << 15) // ring of shadows (invisible shell)
#define EF_INVULNERABILITY (EF_GAME << 16) // invulnerability shell
#define EF_MODULATE        (EF_GAME << 17) // boost mesh brightness

/**
 * @brief The lightning gun overrides animation1 to inform the client what
 * kind of trail to render.
 */
#define LIGHTNING_NO_HIT    0
#define LIGHTNING_SOLID_HIT 1

/**
 * @brief Game-specific entity state trails.
 */
typedef enum {
  TRAIL_BLASTER = TRAIL_GAME,
  TRAIL_GRENADE,
  TRAIL_ROCKET,
  TRAIL_HYPERBLASTER,
  TRAIL_LIGHTNING,
  TRAIL_BFG,
  TRAIL_TELEPORTER,
  TRAIL_GIB,
  TRAIL_FIREBALL,
  TRAIL_HOOK,
  TRAIL_PLAYER_SPAWN,
  TRAIL_QUAKE_NAIL,
  TRAIL_QUAKE_GRENADE,
  TRAIL_LASER,
} g_entity_trail_t;

/**
 * @brief Scoreboard background color hues.
 */
#define TEAM_COLOR_RED    color_hue_red
#define TEAM_COLOR_BLUE   color_hue_blue
#define TEAM_COLOR_YELLOW color_hue_yellow
#define TEAM_COLOR_GREEN  color_hue_green

/**
 * @brief Team ID
 */
typedef enum {
  TEAM_NONE = -1,
  TEAM_RED,
  TEAM_BLUE,
  TEAM_YELLOW,
  TEAM_GREEN,

  MAX_TEAMS
} g_team_id_t;

/**
 * @brief Entity state model number to indicate that the entity is a client.
 * When this is set, the model should be resolved from `CS_CLIENTS`.
 */
#define MODEL_CLIENT 0xff

/**
 * @brief Weapon handedness.
 */
typedef enum {
  HAND_CENTER,
  HAND_RIGHT,
  HAND_LEFT
} g_hand_t;

/**
 * @brief Stock v1.0.79 gameplay identifiers.
 * @details Race remains a non-team mode, but common GAME owns parsing and
 * formatting for this complete identifier set before Race clamps policy.
 */
typedef enum {
  GAMEPLAY_DEATHMATCH = 0,
  GAMEPLAY_INSTAGIB = 1,
  GAMEPLAY_ARENA = 2,

  GAMEPLAY_TEAMS = (1 << 3),

  GAMEPLAY_TEAM_DEATHMATCH = GAMEPLAY_DEATHMATCH | GAMEPLAY_TEAMS,
  GAMEPLAY_TEAM_INSTAGIB = GAMEPLAY_INSTAGIB | GAMEPLAY_TEAMS,
  GAMEPLAY_TEAM_ARENA = GAMEPLAY_ARENA | GAMEPLAY_TEAMS
} g_gameplay_id_t;

/**
 * @brief A stock gameplay identifier and its canonical cvar/menu strings.
 */
typedef struct {
  g_gameplay_id_t id;
  const char *name;
  const char *label;
} g_gameplay_t;

static const g_gameplay_t g_gameplay_modes[] = {
  { GAMEPLAY_DEATHMATCH,      "deathmatch",      "Deathmatch" },
  { GAMEPLAY_TEAM_DEATHMATCH, "team_deathmatch", "Team Deathmatch" },
  { GAMEPLAY_INSTAGIB,        "instagib",        "Instagib" },
  { GAMEPLAY_TEAM_INSTAGIB,   "team_instagib",   "Team Instagib" },
  { GAMEPLAY_ARENA,           "arena",           "Arena" },
  { GAMEPLAY_TEAM_ARENA,      "team_arena",      "Team Arena" },
};

// Current Race code uses the integrated branch's scalar names.
#define GAME_DEATHMATCH GAMEPLAY_DEATHMATCH
#define GAME_INSTAGIB GAMEPLAY_INSTAGIB
#define GAME_ARENA GAMEPLAY_ARENA

/**
 * @brief Item sets select which weapon and ammo roster a map uses.
 */
typedef enum {
  ITEMS_DEFAULT,
  ITEMS_QUAKE
} g_items_t;

// g_item_type_t and g_item_tag_t are defined in bg_item.h

/**
 * @brief Weapon flags provide hints to indicate weapon use.
 */
typedef enum {
  WF_PROJECTILE  = (1 << 0),
  WF_HITSCAN     = (1 << 1),
  WF_TIMED       = (1 << 2),
  WF_EXPLOSIVE   = (1 << 3),
  WF_SHORT_RANGE = (1 << 4),
  WF_MED_RANGE   = (1 << 5),
  WF_LONG_RANGE  = (1 << 6)
} g_weapon_flags_t;

/**
 * @brief Armor attributes.
 */
typedef struct {

  /**
   * @brief Armor type tag.
   */
  g_item_tag_t tag;

  /**
   * @brief Protection fraction against normal damage.
   */
  float normal_protection;

  /**
   * @brief Protection fraction against energy damage.
   */
  float energy_protection;
} g_armor_info_t;

#if defined(__G_LOCAL_H__)

#include "race_logic.h"
#include "race_profile.h"

/**
 * @brief This file will define the game-visible definitions of `g_client_t`
 * and `g_entity_t`. They are much larger than the server-visible definitions,
 * which are intentionally truncated stubs.
 */
typedef struct g_client_s g_client_t;
typedef struct g_entity_s g_entity_t;

/**
 * @brief Spawn flags for `g_entity_t` are set in the level editor.
 */
#define SF_ITEM_TRIGGER  0x00000001
#define SF_ITEM_NO_TOUCH 0x00000002
#define SF_ITEM_HOVER    0x00000004
#define SF_ITEM_HAZARD_RESPAWN 0x00000008

/**
 * @brief These spawn flags are actually set by the game module on entities
 * that are programmatically instantiated.
 */
#define SF_ITEM_DROPPED      0x00010000
#define SF_ITEM_TARGETS_USED 0x00020000

/**
 * @brief Entity flags (`g_entity_locals.flags`). These again are mostly for
 * backwards compatibility with Quake II.
 */
#define FL_FLY        0x00000001
#define FL_SWIM       0x00000002  // implied immunity to drowning
#define FL_GOD_MODE   0x00000004
#define FL_TEAM_SLAVE 0x00000008  // not the first on the team

/**
 * @brief Move types govern the physics dispatch in `G_RunEntity`.
 */
typedef enum {
  MOVE_TYPE_NONE,
  MOVE_TYPE_NO_CLIP,
  MOVE_TYPE_PUSH,
  MOVE_TYPE_STOP,

  MOVE_TYPE_WALK,
  MOVE_TYPE_FLY,
  MOVE_TYPE_BOUNCE
} g_move_type_t;

/**
 * @brief A synonym for readability; `MOVE_TYPE_THINK` implies that the entity's
 * Think function will update its origin and handle other interactions.
 */
#define MOVE_TYPE_THINK MOVE_TYPE_NONE

/**
 * @brief Items are touchable entities that players visit to acquire inventory.
 */
typedef struct g_item_s {

  /**
   * @brief Static definition shared with cgame (classname, model, icon, etc.).
   */
  g_item_def_t def;

  /**
   * @brief Called when a player touches the item; return false to prevent pickup.
   */
  bool (*Pickup)(g_client_t *cl, g_entity_t *it);

  /**
   * @brief Called when the item is activated from inventory.
   */
  void (*Use)(g_client_t *cl, const struct g_item_s *item);

  /**
   * @brief Called to drop the item; returns the dropped entity or `NULL`.
   */
  g_entity_t *(*Drop)(g_client_t *cl, const struct g_item_s *item);

  /**
   * @brief Called every frame for a player holding this weapon.
   */
  void (*Think)(g_client_t *cl);

  /**
   * @brief Precached model index; calculated at init.
   */
  uint16_t model_index;

  /**
   * @brief Precached pickup sound index; calculated at init.
   */
  uint16_t pickup_sound_index;
} g_item_t;

#define EOFS(x) ((ptrdiff_t) offsetof(g_entity_t, x))

/**
 * @brief Movement states.
 */
typedef enum {
  MOVE_STATE_BOTTOM,
  MOVE_STATE_GOING_UP,
  MOVE_STATE_GOING_DOWN,
  MOVE_STATE_TOP,
} g_move_state_t;

/**
 * @brief Physics parameters and think functions for entities which move.
 */
typedef struct {

  /**
   * @brief Starting origin.
   */
  vec3_t start_origin;

  /**
   * @brief Starting angles.
   */
  vec3_t start_angles;

  /**
   * @brief Ending origin.
   */
  vec3_t end_origin;

  /**
   * @brief Ending angles.
   */
  vec3_t end_angles;

  /**
   * @brief Sound played when movement begins.
   */
  uint16_t sound_start;

  /**
   * @brief Sound played while moving.
   */
  uint16_t sound_middle;

  /**
   * @brief Sound played when movement ends.
   */
  uint16_t sound_end;

  /**
   * @brief Acceleration rate.
   */
  float accel;

  /**
   * @brief Constant travel speed, or the final speed of a ramped move.
   */
  float speed;

  /**
   * @brief Initial speed of a ramped move.
   */
  float start_speed;

  /**
   * @brief Deceleration rate.
   */
  float decel;

  /**
   * @brief Total distance to travel.
   */
  float distance;

  /**
   * @brief Time to wait at each end before reversing.
   */
  float wait;

  /**
   * @brief Current movement state.
   */
  g_move_state_t state;

  /**
   * @brief Current target destination.
   */
  vec3_t dest;

  /**
   * @brief Direction of travel.
   */
  vec3_t dir;

  /**
   * @brief Current movement speed.
   */
  float current_speed;

  /**
   * @brief Number of frames the move uses constant speed.
   */
  int32_t const_frames;

  /**
   * @brief Number of frames the move is accelerating.
   */
  int32_t accel_frames;

  /**
   * @brief Number of frames the move is decelerating.
   */
  int32_t decel_frames;

  /**
   * @brief Callback invoked when the move completes.
   */
  void (*Done)(g_entity_t *);
} g_move_info_t;

#define NUM_GIB_MODELS 4
#define NUM_GIB_SOUNDS 3

/**
 * @brief This structure holds references to frequently accessed media.
 */
typedef struct {
  struct g_media_models_t {
    uint16_t gibs[NUM_GIB_MODELS];

    uint16_t grenade;
    uint16_t quake_grenade;
    uint16_t quake_nail;
    uint16_t rocket;
    uint16_t quake_rocket;

    uint16_t fireball;
  } models;

  struct g_media_sounds_t {
    uint16_t gib_hits[NUM_GIB_SOUNDS];
    uint16_t lava[3];
    uint16_t pain[4];

    uint16_t bfg_hit;
    uint16_t bfg_prime;
    uint16_t death[2];
    uint16_t gasp;
    uint16_t gurp;
    uint16_t grenade_hit;
    uint16_t grenade_clang;
    uint16_t grenade_throw;
    uint16_t grenade_tick;
    uint16_t quake_grenade_hit;
    uint16_t quake_nail_hit;
    uint16_t rocket_fly;
    uint16_t lightning_fly;
    uint16_t laser_fly;
    uint16_t quad_attack;
    uint16_t quad_expire;

    uint16_t teleport;
    uint16_t quake_teleport[5];

    uint16_t water_in;
    uint16_t water_out;

    uint16_t weapon_no_ammo;
    uint16_t weapon_switch;

    uint16_t countdown[11];

    uint16_t roar;

    uint16_t chat;

    uint16_t invulnerability_pickup;
    uint16_t invulnerability_expire;
    uint16_t invulnerability_protect;
    uint16_t invisibility_pickup;
    uint16_t invisibility_expire;
  } sounds;

  struct g_media_images_t {
    uint16_t health;
  } images;
} g_media_t;

/**
 * @brief A list of spawn point entities available for player spawning.
 */
typedef struct {

  /**
   * @brief Number of spawn point entities.
   */
  uint32_t count;

  /**
   * @brief Array of spawn point entity pointers.
   */
  g_entity_t **spots;
} g_spawn_points_t;

/**
 * @brief The main structure for all world management. This is cleared at each
 * level load.
 */
typedef struct {

  /**
   * @brief Current server frame number.
   */
  uint32_t frame_num;

  /**
   * @brief Level time in milliseconds.
   */
  uint32_t time;

  /**
   * @brief Descriptive map name (e.g. "Stress Fractures").
   */
  char message[MAX_STRING_CHARS];

  /**
   * @brief Short server map name (e.g. "fractures").
   */
  char name[MAX_QPATH];

  /**
   * @brief Resolved world gravity (maps.lst / worldspawn / g_gravity). Seeded at
   * spawn and on cvar change; hydrated into pm_params_t by G_MovementParams().
   */
  int16_t gravity;

  /**
   * @brief Active gameplay mode.
   */
  g_gameplay_id_t gameplay;

  /**
   * @brief Active item set.
   */
  g_items_t items;

  /**
   * @brief True if team play is active.
   */
  bool teams;

      /**
   * @brief Number of active teams.
   */
  int32_t num_teams;

    /**
   * @brief Map-specified minimum clients override.
   */
  int32_t min_clients_map;

  /**
   * @brief Frag limit; game ends when a player reaches this.
   */
  int32_t frag_limit;

    /**
   * @brief Time limit in minutes; game ends when exceeded.
   */
  int32_t time_limit;

  /**
   * @brief Background music track.
   */
  char music[MAX_STRING_CHARS];

  /**
   * @brief Level time when scores were last updated.
   */
  uint32_t scores_time;

  /**
   * @brief Level time when intermission began.
   */
  uint32_t intermission_time;

  /**
   * @brief Camera origin during intermission.
   */
  vec3_t intermission_origin;

  /**
   * @brief Camera angles during intermission.
   */
  vec3_t intermission_angle;

  /**
   * @brief Entity currently being processed by `G_RunFrame`.
   */
  g_entity_t *current_entity;

  /**
   * @brief Global spawn points (used in non-team modes).
   */
  g_spawn_points_t spawn_points;

  /**
   * @brief Accumulated frag events for this map, POSTed at intermission.
   */
  Vector *frags;

  /**
   * @brief Map-derived Race checkpoint route.
   */
  race_course_t race_course;

  } g_level_t;

/**
 * @brief Means of death.
 */
 typedef enum {
  MOD_UNKNOWN,
  MOD_BLASTER,
  MOD_SHOTGUN,
  MOD_SUPER_SHOTGUN,
  MOD_MACHINEGUN,
  MOD_GRENADE,
  MOD_GRENADE_SPLASH,
  MOD_ROCKET,
  MOD_ROCKET_SPLASH,
  MOD_HYPERBLASTER,
  MOD_HYPERBLASTER_CLIMB,
  MOD_LIGHTNING,
  MOD_LIGHTNING_DISCHARGE,
  MOD_RAILGUN,
  MOD_BFG_LASER,
  MOD_BFG_BLAST,
  MOD_QUAKE_SHOTGUN,
  MOD_QUAKE_SUPER_SHOTGUN,
  MOD_QUAKE_NAILGUN,
  MOD_QUAKE_SUPER_NAILGUN,
  MOD_QUAKE_GRENADE,
  MOD_QUAKE_GRENADE_SPLASH,
  MOD_QUAKE_ROCKET,
  MOD_QUAKE_ROCKET_SPLASH,
  MOD_QUAKE_THUNDERBOLT,
  MOD_QUAKE_THUNDERBOLT_DISCHARGE,
  MOD_WATER,
  MOD_SLIME,
  MOD_LAVA,
  MOD_CRUSH,
  MOD_TELEFRAG,
  MOD_FALLING,
  MOD_SUICIDE,
  MOD_EXPLOSIVE,
  MOD_TRIGGER_HURT,
  MOD_HANDGRENADE,
  MOD_HANDGRENADE_SPLASH,
  MOD_HANDGRENADE_SUICIDE,
  MOD_HANDGRENADE_KAMIKAZE,
  MOD_FIREBALL,
  MOD_HOOK,
  MOD_ACT_OF_GOD,
  MOD_BOB,
  MOD_BALLISTICS_BLASTER,
  MOD_BALLISTICS_SHOTGUN,
  MOD_BALLISTICS_SUPER_SHOTGUN,
  MOD_BALLISTICS_MACHINEGUN,
  MOD_BALLISTICS_GRENADE,
  MOD_BALLISTICS_ROCKET,
  MOD_BALLISTICS_HYPERBLASTER,
  MOD_BALLISTICS_LIGHTNING,
  MOD_BALLISTICS_RAILGUN,
  MOD_BALLISTICS_BFG,
  MOD_BALLISTICS_QUAKE_SHOTGUN,
  MOD_BALLISTICS_QUAKE_SUPER_SHOTGUN,
  MOD_BALLISTICS_QUAKE_NAILGUN,
  MOD_BALLISTICS_QUAKE_SUPER_NAILGUN,
  MOD_BALLISTICS_QUAKE_GRENADE,
  MOD_BALLISTICS_QUAKE_ROCKET,
  MOD_BALLISTICS_QUAKE_THUNDERBOLT,
  MOD_BALLISTICS_LASER,
  MOD_BALLISTICS_GIBLETS,
  MOD_TURRET_BLASTER,
  MOD_TURRET_SHOTGUN,
  MOD_TURRET_SUPER_SHOTGUN,
  MOD_TURRET_MACHINEGUN,
  MOD_TURRET_GRENADE,
  MOD_TURRET_ROCKET,
  MOD_TURRET_HYPERBLASTER,
  MOD_TURRET_LIGHTNING,
  MOD_TURRET_RAILGUN,
  MOD_TURRET_BFG,
  MOD_TURRET_QUAKE_SHOTGUN,
  MOD_TURRET_QUAKE_SUPER_SHOTGUN,
  MOD_TURRET_QUAKE_NAILGUN,
  MOD_TURRET_QUAKE_SUPER_NAILGUN,
  MOD_TURRET_QUAKE_GRENADE,
  MOD_TURRET_QUAKE_ROCKET,
  MOD_TURRET_QUAKE_THUNDERBOLT,
  MOD_TURRET_LASER,
  MOD_TURRET_GIBLETS,
  MOD_FRIENDLY_FIRE = 0x8000000
} g_means_of_death;

/**
 * @brief Damage flags. These can be and often are combined.
 */
#define DMG_RADIUS   0x1  // damage was indirect
#define DMG_ENERGY   0x2  // damage is from an energy based weapon
#define DMG_BULLET   0x4  // damage is from a bullet
#define DMG_NO_ARMOR 0x8  // armor does not protect from this damage
#define DMG_NO_GOD   0x10  // armor and god mode have no effect

/**
 * @brief Damage parameters for `G_Damage`.
 */
typedef struct {

 /**
  * @brief Entity receiving the damage.
  */
  g_entity_t *target;

 /**
  * @brief Entity that dealt the damage (projectile, explosion, etc.).
  */
  g_entity_t *inflictor;

 /**
  * @brief Entity responsible for the damage (player, etc.).
  */
  g_entity_t *attacker;

 /**
  * @brief Direction the damage came from.
  */
  vec3_t dir;

 /**
  * @brief World point where the damage was applied.
  */
  vec3_t point;

 /**
  * @brief Surface normal at the damage point.
  */
  vec3_t normal;

 /**
  * @brief Amount of damage to apply.
  */
  int32_t damage;

 /**
  * @brief Knockback force to apply.
  */
  int32_t knockback;

 /**
  * @brief Damage flags (`DMG_RADIUS`, `DMG_ENERGY`, etc.).
  */
  int32_t flags;

 /**
  * @brief Means of death identifier.
  */
  g_means_of_death mod;
} g_damage_t;

/**
 * @brief Stock v1.0.79 parameters for scattering client giblets.
 */
typedef struct {
  vec3_t origin;
  vec3_t velocity;
  int32_t count;
  float lift;
  bool head;
  int32_t damage;
  int32_t knockback;
  g_entity_t *attacker;
  uint32_t mod;
  uint32_t lifetime;
} g_giblets_t;

/**
 * @brief The name for the CTF skin used in team games.
 */
#define DEFAULT_TEAM_SKIN "ctf"

/**
 * @brief There are four teams in the default game module.
 */
typedef struct {

  /**
   * @brief Team identifier, used for comparison instead of pointer equality.
   */
  g_team_id_t id;

  /**
   * @brief Short team name for HUD display.
   */
  char name[16];

  /**
   * @brief Team skin name.
   */
  char skin[MAX_QPATH];

    /**
   * @brief Spawn point classname.
   */
  char spawn[MAX_QPATH];

  /**
   * @brief Team player colors.
   */
  color_t shirt, pants, helmet;

  /**
   * @brief Team color hue.
   */
  int16_t color;

    /**
   * @brief Team score.
   */
  int16_t score;

    /**
   * @brief Spawn points for this team.
   */
  g_spawn_points_t spawn_points;

  } g_team_t;

/**
 * @brief The default player model
 */
#define DEFAULT_USER_MODEL "qforcer"

/**
 * @brief The default player skin
 */
#define DEFAULT_USER_SKIN "default"

/**
 * @brief The default user info string (name and skin).
 */
#define DEFAULT_USER_INFO "\\name\\newbie\\skin\\" DEFAULT_USER_MODEL "/" DEFAULT_USER_SKIN

/**
 * @brief The full length of a net name, in bytes (including non-printables).
 */
#define MAX_NET_NAME 64

/**
 * @brief The maximum printable length of a net name.
 */
#define MAX_NET_NAME_PRINTABLE 15

/**
 * @brief This structure contains client data that persists over multiple spawns.
 */
typedef struct {

  /**
   * @brief Frame number when the client first entered the game.
   */
  uint32_t first_frame;

  /**
   * @brief Raw user info key-value string.
   */
  char user_info[MAX_INFO_STRING_STRING];

  /**
   * @brief Display name.
   */
  char net_name[MAX_NET_NAME];

  /**
   * @brief Player model/skin path.
   */
  char skin[MAX_QPATH];

  /**
   * @brief Weapon handedness preference.
   */
  g_hand_t hand;

  /**
   * @brief Non-zero if weapons should auto-switch on pickup.
   */
  uint16_t auto_switch;

  /**
   * @brief The player's selected hook style.
   */
  g_hook_style_t hook_style;

  /**
   * @brief Current team assignment.
   */
  g_team_t *team;

  /**
   * @brief Player effect color hue.
   */
  int16_t color;

  /**
   * @brief Player clothing colors.
   */
  color_t shirt, pants, helmet;

  /**
   * @brief Current score.
   */
  int16_t score;

    /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief True if the player has admin privileges.
   */
  bool admin;

  /**
   * @brief Race-owned administrator authority for this exact connection.
   *
   * This is deliberately independent of the common admin flag, player name,
   * userinfo GUID, and durable Race profile association.
   */
  race_admin_session_t race_admin_session;

  /**
   * @brief One-use Race administrator proof challenge for this connection.
   */
  race_admin_challenge_t race_admin_challenge;

  /**
   * @brief Race vote identity and anti-spam state for this exact connection.
   *
   * The identifier is server-generated and is not derived from profile GUID,
   * display name or address. All fields are cleared by the existing connection
   * reset; cooldown and start count are also reset when a level is configured.
   */
  uint64_t race_vote_connection_id;
  uint32_t race_vote_next_start_time;
  uint8_t race_vote_starts;

  /**
   * @brief True if the player is a spectator.
   */
  bool spectator;

  /**
   * @brief Authoritative Race participation mode, independent of team state.
   */
  race_mode_t race_mode;

  /**
   * @brief Per-client Practice respawn transform, retained across respawns only.
   */
  race_stored_spawn_t race_stored_spawn;

  /**
   * @brief True if the player is muted.
   */
  bool muted;

  /**
   * @brief Immutable identity for the current occupant of this client slot.
   * @details Stock client connect clears the persistent block before a
   * replacement is admitted; the module-global allocator remains monotonic.
   */
  uint64_t race_connection_id;

  /**
   * @brief Per-install GUID sent via userinfo, used for stats reporting.
   */
  char guid[MAX_QPATH];

  /**
   * @brief Connection-local association with a validated durable Race profile.
   */
  race_profile_association_t race_profile;
} g_client_persistent_t;

/**
 * @brief This structure is cleared on each spawn, with the persistent structure
 * explicitly copied over to preserve team membership, etc. This structure
 * extends the server-visible definition to provide all of the state management
 * the game module requires.
 */
struct g_client_s {

  /**
   * @brief What the server reads out of a client. This MUST be the first member:
   * the server reads these fields at offset zero, and C guarantees a pointer to
   * a structure points at its first member. Its fields are reached without
   * naming it, so `cl->entity` is the entity bound to this client.
   */
  sv_game_client_t;

  /**
   * @brief Grappling hook state, reset on respawn.
   */
  g_client_hook_t hook;

  /**
   * @brief Data that persists across respawns.
   */
  g_client_persistent_t persistent;

  /**
   * @brief Authoritative state for the client's current Race run.
   */
  race_run_t race_run;

  /**
   * @brief Start zone currently armed for an exit or fresh-jump start.
   */
  g_entity_t *race_start_trigger;

  /**
   * @brief Most recently accepted Practice stage boundary.
   */
  g_entity_t *race_stage_trigger;

  /**
   * @brief Stage boundary whose anchor should override the next spawn.
   */
  g_entity_t *race_stage_restart_trigger;

  /**
   * @brief One-way barriers currently being traversed by this client.
   */
  uint64_t race_oneway_latches;

  /**
   * @brief Latest authoritative pre-acceleration training sample.
   */
  race_strafe_sample_t race_strafe_sample;

  /**
   * @brief Most recently received movement command.
   */
  pm_cmd_t cmd;

  /**
   * @brief Item inventory counts indexed by item index.
   */
  int16_t inventory[ITEM_TOTAL];

  /**
   * @brief Currently active weapon.
   */
  const g_item_t *weapon;

  /**
   * @brief Previously active weapon.
   */
  const g_item_t *prev_weapon;

  /**
   * @brief Weapon currently being switched to.
   */
  const g_item_t *next_weapon;

  /**
   * @brief Inventory index of the current weapon's ammo.
   */
  uint16_t ammo_index;

  /**
   * @brief Current frame button state.
   */
  uint32_t buttons;

  /**
   * @brief Previous frame button state.
   */
  uint32_t old_buttons;

  /**
   * @brief Buttons pressed this frame (edge-triggered).
   */
  uint32_t latched_buttons;

  /**
   * @brief Level time when the weapon think was last called.
   */
  uint32_t weapon_think_time;

  /**
   * @brief Weapon may fire again when time exceeds this.
   */
  uint32_t weapon_fire_time;

  /**
   * @brief Level time when the weapon was last fired.
   */
  uint32_t weapon_fired_time;

  /**
   * @brief Level time when the weapon was last changed.
   */
  uint32_t weapon_change_time;

  /**
   * @brief Water level from the previous frame.
   */
  pm_water_level_t old_water_level;

          /**
   * @brief Alternating barrel index for the Quake nailgun.
   * Odd = right barrel (+2 units), even = left barrel (-2 units).
   */
  uint32_t quake_nailgun_barrel;

  /**
   */
  int16_t damage_armor;

  /**
   * @brief Damage taken to health this frame.
   */
  int16_t damage_health;

  /**
   * @brief Damage inflicted on other clients this frame.
   */
  int16_t damage_inflicted;

  /**
   * @brief Maximum armor the client can carry.
   */
  int16_t max_armor;

  /**
   * @brief Maximum health the client can be boosted to.
   */
  int16_t max_boost_health;

  /**
   * @brief Horizontal speed after the last move.
   */
  float speed;

  /**
   * @brief Current aiming direction angles.
   */
  vec3_t angles;

  /**
   * @brief Aiming direction vectors.
   */
  vec3_t forward, right, up;

  /**
   * @brief Angles received in the last movement command.
   */
  vec3_t cmd_angles;

  /**
   * @brief View kick angles accumulated this frame.
   */
  vec3_t kick_angles;

  /**
   * @brief Client may respawn when time exceeds this.
   */
  uint32_t respawn_time;

  /**
   * @brief Respawn protection expires at this time.
   */
  uint32_t respawn_protection_time;

  /**
   * @brief Level time when the client last touched the ground.
   */
  uint32_t ground_time;

  /**
   * @brief Falling damage becomes eligible when time exceeds this.
   */
  uint32_t boost_time;

  /**
   * @brief Drowning damage becomes eligible when time exceeds this.
   */
  uint32_t drown_time;

  /**
   * @brief Sizzle damage becomes eligible when time exceeds this.
   */
  uint32_t sizzle_time;

  /**
   * @brief Landing event fires when time exceeds this.
   */
  uint32_t land_time;

  /**
   * @brief Client may jump when time exceeds this.
   */
  uint32_t jump_time;

  /**
   * @brief Pain sound may play when time exceeds this.
   */
  uint32_t pain_time;

  /**
   * @brief Footstep sound plays when time exceeds this.
   */
  uint32_t footstep_time;

  /**
   * @brief Primary animation may update when time exceeds this.
   */
  uint32_t animation1_time;

  /**
   * @brief Secondary animation may update when time exceeds this.
   */
  uint32_t animation2_time;

  /**
   * @brief Held grenade detonates when time exceeds this.
   */
  uint32_t grenade_time;

  /**
   * @brief Level time when the client began holding a primed grenade.
   */
  uint32_t grenade_hold_time;

  /**
   * @brief Frame number when the grenade pin was pulled.
   */
  uint32_t grenade_hold_frame;

  /**
   * @brief The grenade entity the client is currently holding.
   */
  g_entity_t *held_grenade;

  /**
   * @brief Pickup message is displayed until time exceeds this.
   */
  uint32_t pickup_msg_time;

  /**
   * @brief Last usable item picked up.
   */
  const g_item_t *last_pickup;

  /**
   * @brief Client may chat when time exceeds this.
   */
  uint32_t chat_time;

  /**
   * @brief Quad damage is active while time is less than this.
   */
  uint32_t quad_damage_time;

  /**
   * @brief Quad damage countdown warning threshold.
   */
  uint32_t quad_countdown_time;

  /**
   * @brief Quad attack sound plays when time exceeds this.
   */
  uint32_t quad_attack_time;

  /**
   * @brief Invisibility is active while time is less than this.
   */
  uint32_t invisibility_time;

  /**
   * @brief Invulnerability is active while time is less than this.
   */
  uint32_t invulnerability_time;

  /**
   * @brief Pentagram countdown warning threshold.
   */
  uint32_t invulnerability_countdown_time;

  /**
   * @brief Client being chased in spectator mode.
   */
  g_client_t *chase_target;

  /**
   * @brief Previously chased client.
   */
  g_client_t *old_chase_target;

  /**
   * @brief Last dropped item, used for variable expansion.
   */
  const g_item_t *last_dropped;

  /**
   * @brief Death-camera transform and timing while `PMF_DEATH_CAM` is set.
   */
  vec3_t death_cam_origin, death_cam_velocity;
  vec3_t death_cam_offset;
  vec3_t death_cam_angles;
  uint32_t death_cam_time;

  /**
   * @brief True if the scoreboard layout flag should be set.
   */
  bool show_scores;

  /**
   * @brief Scores may be sent when time exceeds this.
   */
  uint32_t scores_time;

  };

typedef struct g_client_s g_client_t;

/**
 * @brief The `g_entity_s` structure extends the server stub to
 * provide all of the state management the game module requires.
 */
struct g_entity_s {

  /**
   * @brief What the server reads out of an entity. This MUST be the first member:
   * the server reads these fields at offset zero, and C guarantees a pointer to
   * a structure points at its first member. Its fields are reached without
   * naming it, so `ent->s.origin` is this entity's state origin.
   */
  sv_game_entity_t;

  /**
   * @brief Spawn flags (`SF_ITEM_HOVER`, etc.).
   */
  uint32_t spawn_flags;

  /**
   * @brief Means of death this entity inflicts.
   */
  uint32_t mod;

  /**
   * @brief Entity flags (`FL_GOD_MODE`, etc.).
   */
  uint32_t flags;

  /**
   * @brief Physics move type.
   */
  g_move_type_t move_type;

  /**
   * @brief Physics move parameters and state.
   */
  g_move_info_t move_info;

  /**
   * @brief Clip mask (e.g. `CONTENTS_MASK_CLIP_PROJECTILE`).
   */
  int32_t clip_mask;

  /**
   * @brief General-purpose timestamp.
   */
  uint32_t timestamp;

  /**
   * @brief Time of the last muzzle flash, throttling the flash rate of rapid
   * firing entities independently of how often they actually fire.
   */
  uint32_t flash_time;

  /**
   * @brief Target name to fire when triggered.
   */
  const char *target;

  /**
   * @brief This entity's target name.
   */
  const char *target_name;

  /**
   * @brief Message to print when triggered.
   */
  const char *message;

  /**
   * @brief Team name for multi-entity grouping.
   */
  const char *team;

  /**
   * @brief Cached pointer to the target entity.
   */
  g_entity_t *target_ent;

  /**
   * @brief Movement speed and acceleration parameters.
   */
  float speed, accel, decel;

  /**
   * @brief Direction of movement derived from angles.
   */
  vec3_t move_dir;

  /**
   * @brief Start and end positions for movers.
   */
  vec3_t pos1, pos2;

  /**
   * @brief Linear velocity.
   */
  vec3_t velocity;

  /**
   * @brief Angular velocity.
   */
  vec3_t avelocity;

  /**
   * @brief Entity mass used for physics calculations.
   */
  float mass;

  /**
   * @brief Level time of the next Think invocation.
   */
  uint32_t next_think;

  /**
   * @brief Per-frame think callback.
   */
  void (*Think)(g_entity_t *ent);

  /**
   * @brief Called when a mover is blocked.
   */
  void (*Blocked)(g_entity_t *ent, g_entity_t *other);

  /**
   * @brief Called on entity contact.
   */
  void (*Touch)(g_entity_t *ent, g_entity_t *other, const cm_trace_t *trace);

  /**
   * @brief Called when triggered.
   */
  void (*Use)(g_entity_t *ent, g_entity_t *other, g_entity_t *activator);

  /**
   * @brief Called when damaged.
   */
  void (*Pain)(g_entity_t *ent, g_entity_t *other, int16_t damage, int16_t knockback);

  /**
   * @brief Called when health drops to zero.
   */
  void (*Die)(g_entity_t *ent, g_entity_t *attacker, uint32_t mod);

  /**
   * @brief Cooldown timer for Touch events.
   */
  uint32_t touch_time;

  /**
   * @brief Sound to play when this projectile hits a structural surface.
   */
  uint16_t hit_sound;

  /**
   * @brief Time of the last push interaction.
   */
  uint32_t push_time;

  /**
   * @brief Time of the last water ripple.
   */
  uint32_t ripple_time;

  /**
   * @brief Radius of the last water ripple.
   */
  float ripple_size;

  /**
   * @brief Current health.
   */
  int16_t health;

  /**
   * @brief Maximum health.
   */
  int16_t max_health;

  /**
   * @brief True if the entity is dead.
   */
  bool dead;

  /**
   * @brief True if the entity can receive damage.
   */
  bool take_damage;

  /**
   * @brief Damage dealt on contact.
   */
  int16_t damage;

  /**
   * @brief Knockback applied on contact.
   */
  int16_t knockback;

  /**
   * @brief Radius for splash damage.
   */
  float damage_radius;

  /**
   * @brief General-purpose counter (usage varies by entity type).
   */
  int32_t count;

  /**
   * @brief Current enemy entity.
   */
  g_entity_t *enemy;

  /**
   * @brief Entity that last activated/triggered this entity.
   */
  g_entity_t *activator;

  /**
   * @brief First entity in a team chain.
   */
  g_entity_t *team_master;

  /**
   * @brief Next entity in the team chain.
   */
  g_entity_t *team_next;

  /**
   * @brief Looping ambient sound index.
   */
  uint16_t sound;

  /**
   * @brief Time to wait between activations.
   */
  float wait;

  /**
   * @brief Delay before firing targets after activation.
   */
  float delay;

  /**
   * @brief Random time added to the delay.
   */
  float random;

  /**
   * @brief Ground trace result from the last physics frame.
   */
  cm_trace_t ground;

  /**
   * @brief Content type of water the entity is submerged in.
   */
  int32_t water_type;

  /**
   * @brief Current water immersion level.
   */
  pm_water_level_t water_level;

  /**
   * @brief Item definition for bonus item entities.
   */
  const g_item_t *item;

  /**
   * @brief Projectile definition for `ballistics_*` and `turret_*` entities, resolved from their
   * classname at spawn time. Incomplete here; the definition is private to g_entity_target.c.
   */
  const struct g_ballistics_type_s *ballistics;

  /**
   * @brief AI navigation node for item path tracking.
   */
  ai_node_id_t node;

  /**
   * @brief True if the entity should advance along the item path.
   */
  bool move_node;

  /**
   * @brief Per-client touch times for a Race trigger entity.
   */
  uint32_t *race_touch_times;

  /**
   * @brief Parsed behavior for `trigger_race_start`.
   */
  race_start_mode_t race_start_mode;

  /**
   * @brief True when a configured stage has a unique safe restart anchor.
   */
  bool race_stage_valid;

  /**
   * @brief Race-owned conditional movement brush metadata.
   */
  race_barrier_type_t race_barrier_type;
  race_gate_mode_t race_gate_mode;
  uint16_t race_gate_checkpoint;
  uint8_t race_barrier_id;
  bool race_gate_invert;
  bool race_barrier_valid;

  /**
   * @brief Semantic preset that owned this player-fired projectile.
   * @details Zero remains INVALID for unscoped mapper, turret, death-drop and
   * other legacy projectile callers.
   */
  race_physics_preset_id_t race_physics_preset;

  /**
   * @brief GAME-only weapon movement profile stamped at player fire time.
   */
  race_weapon_profile_id_t race_weapon_profile;

  /**
   * @brief Exact player fire path that constructed this projectile.
   */
  race_weapon_fire_kind_t race_weapon_fire_kind;

  /**
   * @brief Authoritative tuning generation captured for this accepted shot.
   * @details Zero means that the projectile was spawned outside an active
   * tuning session and therefore retains the legacy live-cvar behavior.
   */
  uint64_t race_weapon_tuning_generation;

  /**
   * @brief Impact-time tuning values copied at projectile construction.
   * @details Effective-snapshot mutations clear older projectiles, but these
   * stamps also make the ownership explicit and keep an impact self-contained.
   */
  float race_weapon_self_knockback;
  float race_weapon_hyper_climb_range;
  float race_weapon_hyper_climb_impulse_z;
  float race_weapon_hyper_climb_in;
  float race_weapon_hyper_climb_velocity_boost;
  float race_weapon_hyper_climb_3d;
  float race_weapon_hyper_climb_3d_up;
  float race_weapon_hyper_climb_3d_side;
  float race_weapon_hyper_climb_3d_in;
};

typedef struct g_entity_s g_entity_t;

#endif
