racedatadir = @PKGDATADIR@/race
racemapsdir = $(racedatadir)/maps

racedata_DATA = \
	manifest.mf \
	maps.lst

racemaps_DATA = \
	maps/mzc_dj.bsp \
	maps/mzc_dj.mf \
	maps/potato.bsp \
	maps/potato.mf \
	maps/race-custom-entities.bsp \
	maps/race-custom-entities.mf

EXTRA_DIST = \
	$(racedata_DATA) \
	$(racemaps_DATA)
